[build]
builder = "NIXPACKS"
watchPatterns = ["colmena-backend/**", "colmena-frontend/**"]

[deploy]
startCommand = "echo 'Use service-specific configs'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10